### ISSUE TITLE
[Bug]: llmcompressor not working with transformers4.57.3

### ISSUE THREAD

**Issue by rahulgupta-vs** [vllm-project/llm-compressor#2381]
### ⚙️ Your current environment

from llmcompressor import oneshot
from llmcompressor.modifiers.quantization import AWQModifier

quant_config = AWQModifier(
targets="Linear", # quantize linear layers
scheme="W4A16", # 4-bit weights, 16-bit activations
group_size=128,
)

quantized_model = oneshot(
model=model,
dataset=calibration_data,
recipe=quant_config,
max_seq_length=512,
num_calibration_samples=256,
)

ImportError Traceback (most recent call last)
[/tmp/ipython-input-2484400448.py](https://localhost:8080/#) in <cell line: 0>()
----> 1 from llmcompressor import oneshot
2 from llmcompressor.modifiers.quantization import AWQModifier
3
4 quant_config = AWQModifier(
5 targets="Linear", # quantize linear layers

14 frames
[/usr/local/lib/python3.12/dist-packages/transformers/image_processing_base.py](https://localhost:8080/#) in
25 from .feature_extraction_utils import BatchFeature as BaseBatchFeature
26 from .image_utils import is_valid_image, load_image
---> 27 from .utils import (
28 IMAGE_PROCESSOR_NAME,
29 PROCESSOR_NAME,

ImportError: cannot import name 'download_url' from 'transformers.utils' (/usr/local/lib/python3.12/dist-packages/transformers/utils/init.py)

### 🐛 Describe the bug

when i try to quantize the qwen2.5-16bit model with latest version of llmcompressor 0.9.0.2
then it gives me the error of cannot import name dowload_url from transformers.utils

why latest version gives me this conflicting issue please try to solve this issue
or any other alternative

**Comment by brian-dellabetta** [comment]
Hi @rahulgupta-vs , please provide a complete script so we can try on our end. the snippet you provided contains undefined vars.

**Comment by rahulgupta-vs** [comment]
```python
import torch
import copy
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig, DynamicCache
import types

# 1. Load model
model_name = "Qwen/Qwen2.5-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True
)

tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

# ----------------------------
# Step 1: Copy and Setup New Layer
# ----------------------------
new_layer = copy.deepcopy(model.model.layers[-1])
new_layer.alpha = torch.nn.Parameter(
    torch.zeros(1, device=model.device, dtype=model.dtype)
)

original_forward = new_layer.forward

def scaled_forward(self, hidden_states, *args, **kwargs):
    input_hidden = hidden_states
    outputs = original_forward(hidden_states, *args, **kwargs)
    if isinstance(outputs, tuple):
        hidden_out, rest = outputs[0], outputs[1:]
    else:
        hidden_out, rest = outputs, None

    # Apply the residual identity logic: y = x + alpha * (f(x) - x)
    hidden_out = input_hidden + self.alpha * (hidden_out - input_hidden)
    print("hidden output shape" , hidden_out.shape)
    return (hidden_out,) + rest if rest is not None else hidden_out

new_layer.forward = types.MethodType(scaled_forward, new_layer)

# ----------------------------
# Step 2: Critical Structural Update
# ----------------------------
# Convert to list, append, then RE-REGISTER as a ModuleList
layer_list = list(model.model.layers)
layer_list.append(new_layer)
model.model.layers = torch.nn.ModuleList(layer_list)

# Update ALL config locations
num_layers = len(model.model.layers)
model.config.num_hidden_layers = num_layers
model.model.config.num_hidden_layers = num_layers
model.config.layer_types.append(model.config.layer_types[-1])


# Re-index every layer specifically for the Attention mechanics
for i, layer in enumerate(model.model.layers):
    if hasattr(layer.self_attn, 'layer_idx'):
        layer.self_attn.layer_idx = i
    layer.layer_idx = i

# Reset generation config
model.generation_config = GenerationConfig.from_model_config(model.config)
model.eval()

print(f"Model expanded successfully to {num_layers} layers.")
print(f"Model expanded successfully to {model.config.num_hidden_layers} layers.")
print(f"Model expanded successfully to {len(model.config.layer_types)} layers.")

model.save_pretrained("./valiance-1.5-instruct-16")
tokenizer.save_pretrained("./valiance-1.5-instruct-16")



import torch
import copy
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig, DynamicCache
import types

model_path = "valiance-1.5-instruct-16"
tokenizer = AutoTokenizer.from_pretrained(model_path,trust_remote_code=True)
model1 = AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    device_map="auto",
    dtype=torch.bfloat16  # Use dtype instead of deprecated torch_dtype
)
layer = model1.model.layers[28]

layer.alpha = torch.nn.Parameter(
    torch.zeros(1, device=model1.device, dtype=model1.dtype)
)

original_forward = layer.forward

def scaled_forward(self, hidden_states, *args, **kwargs):
    input_hidden = hidden_states
    outputs = original_forward(hidden_states, *args, **kwargs)
    if isinstance(outputs, tuple):
        hidden_out, rest = outputs[0], outputs[1:]
    else:
        hidden_out, rest = outputs, None

    hidden_out = input_hidden + self.alpha * (hidden_out - input_hidden)

    return (hidden_out,) + rest if rest is not None else hidden_out

import types
layer.forward = types.MethodType(scaled_forward, layer)


from datasets import load_dataset

dataset = load_dataset(
    "wikitext",
    "wikitext-2-raw-v1",
    split="train[:512]"
)

def preprocess(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding=False,
        max_length=512,
    )

calibration_data = dataset.map(preprocess)

from llmcompressor.modifiers.awq import AWQModifier
from llmcompressor import oneshot

quant_config = AWQModifier(
    targets=["Linear"],
    scheme="W4A16",
    ignore=["lm_head"],
)

quantized_model = oneshot(
    model=model1,
    tokenizer=tokenizer,
    dataset=calibration_data,
    recipe=quant_config,
    max_seq_length=512,
    num_calibration_samples=256,
)
```
as i have a custom qwen2.5-1.5B-Instruct model which i'm loading but when i try to quantize its not working getting error like 
TypeError: missing a required argument: 'input'

**Comment by brian-dellabetta** [comment]
Hi @rahulgupta-vs , let's cover this in the other issue you created. There is likely something wrong with your code hacking into the model, beyond scope of the support we provide.

```python
model_path = "valiance-1.5-instruct-16"
tokenizer = AutoTokenizer.from_pretrained(model_path,trust_remote_code=True)
model1 = AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    device_map="auto",
    dtype=torch.bfloat16  # Use dtype instead of deprecated torch_dtype
)
layer = model1.model.layers[28]

layer.alpha = torch.nn.Parameter(
    torch.zeros(1, device=model1.device, dtype=model1.dtype)
)

original_forward = layer.forward

def scaled_forward(self, hidden_states, *args, **kwargs):
    input_hidden = hidden_states
    outputs = original_forward(hidden_states, *args, **kwargs)
    if isinstance(outputs, tuple):
        hidden_out, rest = outputs[0], outputs[1:]
    else:
        hidden_out, rest = outputs, None

    hidden_out = input_hidden + self.alpha * (hidden_out - input_hidden)

    return (hidden_out,) + rest if rest is not None else hidden_out

import types
layer.forward = types.MethodType(scaled_forward, layer)
```

Closing in favor of #2397
