### PR TITLE
[TRL_SFT_Trainer] Fix and Update Examples code

### PR DESCRIPTION
**Pull request by horheynm**
SUMMARY:
* Fix examples script failure https://github.com/neuralmagic/llm-compressor-testing/actions/runs/13350457472/job/37286313648

PROBLEM
1. 
```bash
 cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
TypeError: SessionManagerMixIn.__init__() missing 2 required positional arguments: 'data_args' and 'model_args'

```

2.
```bash
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
TypeError: SFTTrainer.__init__() got an unexpected keyword argument 'max_seq_length'
```

3.
```bash
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
AttributeError: 'NoneType' object has no attribute 'save_compressed'
```

4.
```
(.venv) gohashi@janice:~/llm-compressor$ cpy 2 '/home/gohashi/llm-compressor/examples/trl_mixin/ex_trl_constant.py'
...
/home/gohashi/llm-compressor/src/llmcompressor/transformers/finetune/session_mixin.py:97: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
...
```

SOLUTION:
1. Caused by https://github.com/vllm-project/llm-compressor/pull/1103/files#diff-059b8cf7e48691cd2d5ddda1d0ba5f584657a70c5804797d38c902b433777335R69-R70, where `model_args` and `data_args` is required. Add it to the code and make `model_args` and `data_args` optional
2. `max_seq_length` is not a part of `TrainingArgs`, which gets called by super first. We see that it is used in `SFTConfig` that inherits `TRLSFTConfig` where `max_seq_length` is used.  `TRLSFTConfig` inherits `TrainingArguments` to modify the code.
3. Make `model_args` required
4. Bug warning. Update `tokenizer` to `processing_class`

TEST PLAN:
* Pass`[examples/trl_mixin/ex_trl_constant.py](https://github.com/vllm-project/llm-compressor/compare/sessionmixin-revert-signature?expand=1#diff-f14ef5a7e5c54f35e347fd75ed37e39b8f6db081199bd6233cf14d2c1b4bdef9)`
* Pass existing tests

### CODE REVIEW

File: examples/trl_mixin/sft_trainer.py [hunk 1]
```diff
@@ -10,11 +9,9 @@
 class SFTTrainer(SessionManagerMixIn, TRLSFTTrainer):
     def __init__(self, *args, **kwargs):
         sft_config_args = kwargs.get("args")
-        if (
-            sft_config_args is not None
-            and sft_config_args.__class__.__name__ == "TrainingArguments"
-        ):
-            kwargs["args"] = SFTConfig(**sft_config_args.to_dict())
+        if sft_config_args is not None:
+            kwargs["args"] = TRLSFTConfig(**sft_config_args)
```
Comment (brian-dellabetta) [inline examples/trl_mixin/sft_trainer.py:13]: to help with readability, could this be:
```python
def __init__(self, training_args: Optional[TrainingArguments] = None, *args, **kwargs):
    if training_args is not None:
        kwargs["args"] = TRLSFTConfig(**training_args)
```
and modify the invocation [here](https://github.com/vllm-project/llm-compressor/pull/1161/files#diff-f14ef5a7e5c54f35e347fd75ed37e39b8f6db081199bd6233cf14d2c1b4bdef9R58) accordingly? If it's just an example file we should be ok to change?

**Review by brian-dellabetta — DISMISSED** [review]

File: examples/trl_mixin/ex_trl_constant.py [hunk 2]
```diff
@@ -39,21 +39,23 @@ def formatting_prompts_func(example):
 response_template = "Answer:"
 collator = DataCollatorForCompletionOnlyLM(response_template, tokenizer=tokenizer)
 
-training_args = TrainingArguments(
+training_args = dict(
     output_dir=output_dir,
-    num_train_epochs=0.6,
+    num_train_epochs=0.1,
```
Comment (kylesayrs) [inline examples/trl_mixin/ex_trl_constant.py:44]: I assume 0.6 is a good number to demonstrate for the example, is there a reason why it should be changed?

Comment (horheynm) [reply examples/trl_mixin/ex_trl_constant.py:44]: Sorry I changed it back

File: examples/trl_mixin/sft_trainer.py (hunk 1 above)
Comment (horheynm) [reply examples/trl_mixin/sft_trainer.py:13]: Ok I can do that

**Review by dsikka — APPROVED** [review]

**Review by rahul-tuli — APPROVED** [review]

**Review by brian-dellabetta — APPROVED** [review]
👍

**Comment by horheynm** [comment]
I still need to fix ex_trl_distillation.py, hold merge please
